### ISSUE TITLE
Failed to load the mylyn-for-atom package

### ISSUE THREAD

**Issue by senpl** [mlp1802/mylyn-for-atom#3]
[Enter steps to reproduce:]

1.update mylyn-for-atom in atom v.1.33.0
2. update version of atom to 1.36.0

**Atom**: 1.36.0 x64
**Electron**: 2.0.18
**OS**: Ubuntu 18.04
**Thrown From**: [mylyn-for-atom](https://github.com/mlp1802/mylyn-for-atom) package 1.22.0

### Stack Trace

Failed to load the mylyn-for-atom package

```
At Cannot find module 'space-pen'

Error: Cannot find module 'space-pen'
    at Module._resolveFilename (module.js:543:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (/usr/share/atom/resources/app/static/<embedded>:11:154765)
    at Module.require (/app.asar/static/index.js:40:43)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146072)
    at /packages/compare-files/node_modules/atom-space-pen-views/lib/main.js:4:10)
    at /packages/compare-files/node_modules/atom-space-pen-views/lib/main.js:22:4)
    at /packages/compare-files/node_modules/atom-space-pen-views/lib/main.js:24:3)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:146782)
    at Object.value [as .js] (/usr/share/atom/resources/app/static/<embedded>:11:150329)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146072)
    at /packages/mylyn-for-atom/lib/TaskList.coffee:1:26)
    at /packages/mylyn-for-atom/lib/TaskList.coffee:1:1)
    at /packages/mylyn-for-atom/lib/TaskList.coffee:1:1)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:146782)
    at Object.value [as .coffee] (/usr/share/atom/resources/app/static/<embedded>:11:150329)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (/app.asar/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/static/<embedded>:11:146072)
    at /packages/mylyn-for-atom/lib/mylyn.coffee:1:23)
    at /packages/mylyn-for-atom/lib/mylyn.coffee:1:1)
    at /packages/mylyn-for-atom/lib/mylyn.coffee:1:1)
    at Module.get_Module._compile (/usr/share/atom/resources/app/static/<embedded>:11:146782)
    at Object.value [as .coffee] (/usr/share/atom/resources/app/static/<embedded>:11:150329)
```

### Commands

```
```

### Non-Core Packages

```
atom-autocomplete-php 0.25.6 
atom-beautify 0.33.4 
atom-quokka 1.0.69 
atom-runner 2.7.1 
atom-shell-commands 1.5.0 
autocomplete-modules 2.3.0 
bottom-dock 0.4.4 
busy-signal 2.0.1 
comment-down 0.1.1 
compare-files 0.8.1 
dash 1.7.1 
dev-tools-dark 0.5.0 
dev-tools-themes 0.1.3 
file-icons 2.1.31 
find-selection 0.16.0 
fold-comments 0.6.0 
fold-functions 0.11.0 
foldingtext-for-atom 0.9.2 
ftp-remote-edit 0.15.2 
git-clone 0.2.0 
git-control 0.9.0 
git-plus 7.10.2 
gitlab 0.1.3-7 
hyperclick 0.1.5 
intentions 1.1.5 
js-hyperclick 1.17.0 
jump-to-import 3.6.5 
jumpy 5.0.2 
language-babel undefined 
language-groovy 0.7.0 
language-log 1.10.1 
linter 2.3.0 
linter-eslint 8.4.1 
linter-ui-default 1.7.1 
minimap 4.29.9 
mylyn-for-atom 1.22.0 
node-debugger 1.10.1 
organized 0.8.1 
package-cop 0.2.10 
php-debug 0.2.6 
php-server 0.8.0 
preview 0.17.0 
quick-log 0.3.1 
rabbitvcs-svn 0.6.0 
remote-edit 1.9.0 
script 3.17.3 
simple-drag-drop-text 0.4.0 
svn 0.0.14 
sync-settings 0.8.6 
tabs-to-spaces 1.0.5 
tasks 2.10.1 
todo-manager 0.2.10 
todo-show 2.3.0 
tool-bar 1.1.11 
tool-bar-almighty 0.9.0 
tool-bar-main 0.0.11 
tool-bar-shortcuts 0.1.5 
trailing-spaces 0.4.0 
tree-view-finder 0.2.1 
turbo-javascript 1.4.0 
xml-formatter 0.11.0 
zentabs 0.8.9 
```

**Comment by mlp1802** [comment]
Thanks will have a look at it.
